CREATE TABLE IF NOT EXISTS users
(
    id          BIGINT       NOT NULL AUTO_INCREMENT PRIMARY KEY,
    username    VARCHAR(255) NOT NULL UNIQUE,
    password    VARCHAR(255) NOT NULL,
    access_role VARCHAR(255) NOT NULL
);